version: '3.5'

networks:
  secondLife-network:
    driver: bridge

volumes: # add this section
  secondlife-pg-volume:
  secondlife-redis-volume:

services:
  db:
    container_name: secondlife-database-pg-${NODE_ENV}
    image: postgres:15.2
    restart: always
    env_file:
      - .env
    networks:
      - secondlife-network
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - secondlife-pg-volume:/var/lib/pg/data
    ports:
      - ${DB_PORT}:5432
  redis:
    container_name: secondlife-redis-${NODE_ENV}
    image: redis:7.2.4
    restart: always
    env_file:
      - .env
    networks:
      - secondlife-network
    volumes:
      - secondlife-redis-volume:/data
    ports:
      - ${REDIS_PORT}:6379
  app:
    container_name: secondlife-app-container-${NODE_ENV}
    build:
      context: .
      target: production
    env_file:
      - .env
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - ${PORT}:${PORT}
    networks:
      - secondlife-network
    depends_on:
      - db
      - redis
